leaf.name=com.sankuai.leaf.opensource.test
leaf.segment.enable=true
leaf.jdbc.url=jdbc:mysql://192.168.1.3:3306/leaf?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
leaf.jdbc.username=root
leaf.jdbc.password=hsy1114

leaf.snowflake.enable=true
leaf.snowflake.zk.address=192.168.1.4:2181
leaf.snowflake.port=2222